Scheduler/grails-app/domain/scheduler/Room.groovy
package scheduler

class Room {
	String roomName
	int maxAllowed
	boolean projector
	boolean whiteboard
	boolean tvScreens
	boolean speakerSystem
	
	Room(String roomName, int maxAllowed, boolean projector, boolean whiteboard, boolean tvScreens, boolean speakerSystem){
		this.roomName = roomName
		this.maxAllowed = maxAllowed
		this.projector = projector
		this.whiteboard = whiteboard
		this.tvScreens = tvScreens
		this.speakerSystem = speakerSystem
	}

    static constraints = {
    	roomName			blank : false
		maxAllowed			min : 0
		projector			blank : false
		whiteboard			blank : false
		tvScreens			blank : false
		speakerSystem		blank : false
    }
}

Scheduler/grails-app/controllers/scheduler/RoomController.groovy
package scheduler

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class RoomController {
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Room.list(params), model:[roomInstanceCount: Room.count()]
    }

    def show(Room roomInstance) {
        respond roomInstance
    }

    def create() {
        respond new Room(params)
    }

    @Transactional
    def save(Room roomInstance) {
        if (roomInstance == null) {
            notFound()
            return
        }
        if (roomInstance.hasErrors()) {
            respond roomInstance.errors, view:'create'
            return
        }
        roomInstance.save flush:true
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'room.label', default: 'Room'), roomInstance.id])
                redirect roomInstance
            }
            '*' { respond roomInstance, [status: CREATED] }
        }
    }

    def edit(Room roomInstance) {
        respond roomInstance
    }

    @Transactional
    def update(Room roomInstance) {
        if (roomInstance == null) {
            notFound()
            return
        }
        if (roomInstance.hasErrors()) {
            respond roomInstance.errors, view:'edit'
            return
        }
        roomInstance.save flush:true
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Room.label', default: 'Room'), roomInstance.id])
                redirect roomInstance
            }
            '*'{ respond roomInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Room roomInstance) {
        if (roomInstance == null) {
            notFound()
            return
        }
        roomInstance.delete flush:true
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Room.label', default: 'Room'), roomInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'room.label', default: 'Room'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Scheduler/grails-app/views/room/_form.gsp
<%@ page import="scheduler.Room" %>



<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'roomName', 'error')} required">
	<label for="roomName">
		<g:message code="room.roomName.label" default="Room Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="roomName" required="" value="${roomInstance?.roomName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'maxAllowed', 'error')} required">
	<label for="maxAllowed">
		<g:message code="room.maxAllowed.label" default="Max Allowed" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="maxAllowed" type="number" min="0" value="${roomInstance.maxAllowed}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'projector', 'error')} ">
	<label for="projector">
		<g:message code="room.projector.label" default="Projector" />
		
	</label>
	<g:checkBox name="projector" value="${roomInstance?.projector}" />

</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'whiteboard', 'error')} ">
	<label for="whiteboard">
		<g:message code="room.whiteboard.label" default="Whiteboard" />
		
	</label>
	<g:checkBox name="whiteboard" value="${roomInstance?.whiteboard}" />

</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'tvScreens', 'error')} ">
	<label for="tvScreens">
		<g:message code="room.tvScreens.label" default="Tv Screens" />
		
	</label>
	<g:checkBox name="tvScreens" value="${roomInstance?.tvScreens}" />

</div>

<div class="fieldcontain ${hasErrors(bean: roomInstance, field: 'speakerSystem', 'error')} ">
	<label for="speakerSystem">
		<g:message code="room.speakerSystem.label" default="Speaker System" />
		
	</label>
	<g:checkBox name="speakerSystem" value="${roomInstance?.speakerSystem}" />

</div>

Scheduler/grails-app/views/room/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-room" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-room" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${roomInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${roomInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:roomInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Scheduler/grails-app/views/room/edit.gsp
<%@ page import="scheduler.Room" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-room" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-room" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${roomInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${roomInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:roomInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${roomInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Scheduler/grails-app/views/room/index.gsp
<%@ page import="scheduler.Room" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-room" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-room" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="roomName" title="${message(code: 'room.roomName.label', default: 'Room Name')}" />
					
						<g:sortableColumn property="maxAllowed" title="${message(code: 'room.maxAllowed.label', default: 'Max Allowed')}" />
					
						<g:sortableColumn property="projector" title="${message(code: 'room.projector.label', default: 'Projector')}" />
					
						<g:sortableColumn property="whiteboard" title="${message(code: 'room.whiteboard.label', default: 'Whiteboard')}" />
					
						<g:sortableColumn property="tvScreens" title="${message(code: 'room.tvScreens.label', default: 'Tv Screens')}" />
					
						<g:sortableColumn property="speakerSystem" title="${message(code: 'room.speakerSystem.label', default: 'Speaker System')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${roomInstanceList}" status="i" var="roomInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${roomInstance.id}">${fieldValue(bean: roomInstance, field: "roomName")}</g:link></td>
					
						<td>${fieldValue(bean: roomInstance, field: "maxAllowed")}</td>
					
						<td><g:formatBoolean boolean="${roomInstance.projector}" /></td>
					
						<td><g:formatBoolean boolean="${roomInstance.whiteboard}" /></td>
					
						<td><g:formatBoolean boolean="${roomInstance.tvScreens}" /></td>
					
						<td><g:formatBoolean boolean="${roomInstance.speakerSystem}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${roomInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Scheduler/grails-app/views/room/show.gsp
<%@ page import="scheduler.Room" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-room" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-room" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list room">
			
				<g:if test="${roomInstance?.roomName}">
				<li class="fieldcontain">
					<span id="roomName-label" class="property-label"><g:message code="room.roomName.label" default="Room Name" /></span>
					
						<span class="property-value" aria-labelledby="roomName-label"><g:fieldValue bean="${roomInstance}" field="roomName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${roomInstance?.maxAllowed}">
				<li class="fieldcontain">
					<span id="maxAllowed-label" class="property-label"><g:message code="room.maxAllowed.label" default="Max Allowed" /></span>
					
						<span class="property-value" aria-labelledby="maxAllowed-label"><g:fieldValue bean="${roomInstance}" field="maxAllowed"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${roomInstance?.projector}">
				<li class="fieldcontain">
					<span id="projector-label" class="property-label"><g:message code="room.projector.label" default="Projector" /></span>
					
						<span class="property-value" aria-labelledby="projector-label"><g:formatBoolean boolean="${roomInstance?.projector}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${roomInstance?.whiteboard}">
				<li class="fieldcontain">
					<span id="whiteboard-label" class="property-label"><g:message code="room.whiteboard.label" default="Whiteboard" /></span>
					
						<span class="property-value" aria-labelledby="whiteboard-label"><g:formatBoolean boolean="${roomInstance?.whiteboard}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${roomInstance?.tvScreens}">
				<li class="fieldcontain">
					<span id="tvScreens-label" class="property-label"><g:message code="room.tvScreens.label" default="Tv Screens" /></span>
					
						<span class="property-value" aria-labelledby="tvScreens-label"><g:formatBoolean boolean="${roomInstance?.tvScreens}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${roomInstance?.speakerSystem}">
				<li class="fieldcontain">
					<span id="speakerSystem-label" class="property-label"><g:message code="room.speakerSystem.label" default="Speaker System" /></span>
					
						<span class="property-value" aria-labelledby="speakerSystem-label"><g:formatBoolean boolean="${roomInstance?.speakerSystem}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:roomInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${roomInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>