Scheduler/grails-app/domain/scheduler/Subject.groovy
package scheduler

class Subject {
	String subjectName
	String subjectTeacher
	String studentsEnrolled
	int subjectWeekStart
	int subjectWeekEnd
	int subjectYear
		
	Subject(String subjectName,	String subjectTeacher, String studentsEnrolled, int subjectWeekStart,	int subjectWeekEnd,
					int subjectYear){
						this.subjectName = subjectName
						this.subjectTeacher = subjectTeacher
						this.studentsEnrolled = studentsEnrolled
						this.subjectWeekStart = subjectWeekStart
						this.subjectWeekEnd = subjectWeekEnd
						this.subjectYear = subjectYear
					}

    static constraints = {
		subjectName			blank : false
		subjectTeacher		blank : false
		studentsEnrolled	blank : false, size:0..10000
		subjectWeekStart	min : 0
		subjectWeekEnd		min : 0
		subjectYear			min : 0
	}
}

Scheduler/grails-app/controllers/scheduler/SubjectController.groovy
package scheduler

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class SubjectController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Subject.list(params), model:[subjectInstanceCount: Subject.count()]
    }

    def show(Subject subjectInstance) {
        respond subjectInstance
    }

    def create() {
        respond new Subject(params)
    }

    @Transactional
    def save(Subject subjectInstance) {
        if (subjectInstance == null) {
            notFound()
            return
        }
        if (subjectInstance.hasErrors()) {
            respond subjectInstance.errors, view:'create'
            return
        }
        subjectInstance.save flush:true
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'subject.label', default: 'Subject'), subjectInstance.id])
                redirect subjectInstance
            }
            '*' { respond subjectInstance, [status: CREATED] }
        }
    }

    def edit(Subject subjectInstance) {
        respond subjectInstance
    }

    @Transactional
    def update(Subject subjectInstance) {
        if (subjectInstance == null) {
            notFound()
            return
        }
        if (subjectInstance.hasErrors()) {
            respond subjectInstance.errors, view:'edit'
            return
        }
        subjectInstance.save flush:true
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Subject.label', default: 'Subject'), subjectInstance.id])
                redirect subjectInstance
            }
            '*'{ respond subjectInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Subject subjectInstance) {
        if (subjectInstance == null) {
            notFound()
            return
        }
        subjectInstance.delete flush:true
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Subject.label', default: 'Subject'), subjectInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'subject.label', default: 'Subject'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Scheduler/grails-app/views/subject/_form.gsp
<%@ page import="scheduler.Subject" %>



<div class="fieldcontain ${hasErrors(bean: subjectInstance, field: 'subjectName', 'error')} required">
	<label for="subjectName">
		<g:message code="subject.subjectName.label" default="Subject Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="subjectName" required="" value="${subjectInstance?.subjectName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: subjectInstance, field: 'subjectTeacher', 'error')} required">
	<label for="subjectTeacher">
		<g:message code="subject.subjectTeacher.label" default="Subject Teacher" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="subjectTeacher" required="" value="${subjectInstance?.subjectTeacher}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: subjectInstance, field: 'studentsEnrolled', 'error')} required">
	<label for="studentsEnrolled">
		<g:message code="subject.studentsEnrolled.label" default="Students Enrolled" />
		<span class="required-indicator">*</span>
	</label>
	<g:textArea name="studentsEnrolled" cols="40" rows="5" maxlength="10000" required="" value="${subjectInstance?.studentsEnrolled}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: subjectInstance, field: 'subjectWeekStart', 'error')} required">
	<label for="subjectWeekStart">
		<g:message code="subject.subjectWeekStart.label" default="Subject Week Start" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="subjectWeekStart" type="number" min="0" value="${subjectInstance.subjectWeekStart}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: subjectInstance, field: 'subjectWeekEnd', 'error')} required">
	<label for="subjectWeekEnd">
		<g:message code="subject.subjectWeekEnd.label" default="Subject Week End" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="subjectWeekEnd" type="number" min="0" value="${subjectInstance.subjectWeekEnd}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: subjectInstance, field: 'subjectYear', 'error')} required">
	<label for="subjectYear">
		<g:message code="subject.subjectYear.label" default="Subject Year" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="subjectYear" type="number" min="0" value="${subjectInstance.subjectYear}" required=""/>

</div>

Scheduler/grails-app/views/subject/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subject.label', default: 'Subject')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-subject" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-subject" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${subjectInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${subjectInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:subjectInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Scheduler/grails-app/views/subject/edit.gsp
<%@ page import="scheduler.Subject" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subject.label', default: 'Subject')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-subject" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-subject" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${subjectInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${subjectInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:subjectInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${subjectInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Scheduler/grails-app/views/subject/index.gsp
<%@ page import="scheduler.Subject" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subject.label', default: 'Subject')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-subject" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-subject" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="subjectName" title="${message(code: 'subject.subjectName.label', default: 'Subject Name')}" />
					
						<g:sortableColumn property="subjectTeacher" title="${message(code: 'subject.subjectTeacher.label', default: 'Subject Teacher')}" />
					
						<g:sortableColumn property="studentsEnrolled" title="${message(code: 'subject.studentsEnrolled.label', default: 'Students Enrolled')}" />
					
						<g:sortableColumn property="subjectWeekStart" title="${message(code: 'subject.subjectWeekStart.label', default: 'Subject Week Start')}" />
					
						<g:sortableColumn property="subjectWeekEnd" title="${message(code: 'subject.subjectWeekEnd.label', default: 'Subject Week End')}" />
					
						<g:sortableColumn property="subjectYear" title="${message(code: 'subject.subjectYear.label', default: 'Subject Year')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${subjectInstanceList}" status="i" var="subjectInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${subjectInstance.id}">${fieldValue(bean: subjectInstance, field: "subjectName")}</g:link></td>
					
						<td>${fieldValue(bean: subjectInstance, field: "subjectTeacher")}</td>
					
						<td>${fieldValue(bean: subjectInstance, field: "studentsEnrolled")}</td>
					
						<td>${fieldValue(bean: subjectInstance, field: "subjectWeekStart")}</td>
					
						<td>${fieldValue(bean: subjectInstance, field: "subjectWeekEnd")}</td>
					
						<td>${fieldValue(bean: subjectInstance, field: "subjectYear")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${subjectInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Scheduler/grails-app/views/subject/show.gsp
<%@ page import="scheduler.Subject" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subject.label', default: 'Subject')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-subject" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-subject" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list subject">
			
				<g:if test="${subjectInstance?.subjectName}">
				<li class="fieldcontain">
					<span id="subjectName-label" class="property-label"><g:message code="subject.subjectName.label" default="Subject Name" /></span>
					
						<span class="property-value" aria-labelledby="subjectName-label"><g:fieldValue bean="${subjectInstance}" field="subjectName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${subjectInstance?.subjectTeacher}">
				<li class="fieldcontain">
					<span id="subjectTeacher-label" class="property-label"><g:message code="subject.subjectTeacher.label" default="Subject Teacher" /></span>
					
						<span class="property-value" aria-labelledby="subjectTeacher-label"><g:fieldValue bean="${subjectInstance}" field="subjectTeacher"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${subjectInstance?.studentsEnrolled}">
				<li class="fieldcontain">
					<span id="studentsEnrolled-label" class="property-label"><g:message code="subject.studentsEnrolled.label" default="Students Enrolled" /></span>
					
						<span class="property-value" aria-labelledby="studentsEnrolled-label"><g:fieldValue bean="${subjectInstance}" field="studentsEnrolled"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${subjectInstance?.subjectWeekStart}">
				<li class="fieldcontain">
					<span id="subjectWeekStart-label" class="property-label"><g:message code="subject.subjectWeekStart.label" default="Subject Week Start" /></span>
					
						<span class="property-value" aria-labelledby="subjectWeekStart-label"><g:fieldValue bean="${subjectInstance}" field="subjectWeekStart"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${subjectInstance?.subjectWeekEnd}">
				<li class="fieldcontain">
					<span id="subjectWeekEnd-label" class="property-label"><g:message code="subject.subjectWeekEnd.label" default="Subject Week End" /></span>
					
						<span class="property-value" aria-labelledby="subjectWeekEnd-label"><g:fieldValue bean="${subjectInstance}" field="subjectWeekEnd"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${subjectInstance?.subjectYear}">
				<li class="fieldcontain">
					<span id="subjectYear-label" class="property-label"><g:message code="subject.subjectYear.label" default="Subject Year" /></span>
					
						<span class="property-value" aria-labelledby="subjectYear-label"><g:fieldValue bean="${subjectInstance}" field="subjectYear"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:subjectInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${subjectInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>